{{- if .Values.base64_files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiv.fullname" . }}-secret-files
  labels:
{{ include "aiv.labels" . | indent 4 }}
type: Opaque
data:
{{- range $path, $content := .Values.base64_files }}
  {{ $path }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}

{{- if .Values.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiv.fullname" . }}-business-env
  labels:
    {{- include "aiv.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}

