name: Build Debian Package

on:
  push:
    tags: [ 'debian/*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get run.jar from Docker image
      run: |
        docker pull jits023/aiv:6.3.4
        docker create --name aiv_container jits023/aiv:6.3.4
        docker cp aiv_container:/opt/run.jar aiv.jar
        docker rm -f aiv_container

    - name: Install dependencies
      run: sudo apt-get install -y debhelper

    - name: Build debian package
      if: startsWith(github.ref, 'refs/tags/debian/')
      run: |
        export VERSION=$(echo $TAG | sed 's/debian\///')
        DEBUG=1 bash aiv-build-deb.sh

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          aiv-*.deb
