name: Release Debian package

on:
  push:
    branches:
      - main
    paths:
      - "debian/changelog"

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Parse Version from debian/changelog
      id: parse_version
      run: |
        # Extract the latest version from the changelog
        VERSION=$(awk '/^aiv / {gsub(/[()]/, "", $2); print $2; exit}' debian/changelog)
        echo "Latest version found in changelog: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get run.jar from Docker image
      run: |
        export IMAGE_VERSION=${VERSION%%-*}
        echo "Using image version: $IMAGE_VERSION"
        docker pull jits023/aiv:${IMAGE_VERSION}
        docker create --name aiv_container jits023/aiv:${IMAGE_VERSION}
        docker cp aiv_container:/opt/run.jar aiv.jar
        docker rm -f aiv_container

    - name: Build Debian package
      run: |
        echo "Building Debian package for version $VERSION"
        docker run --rm -e "VERSION=$VERSION" \
          -v $PWD:/workspace \
          -w /workspace \
          debian:12 \
          bash -c "apt-get update && apt-get install -y debhelper && \
                   DEBUG=1 bash aiv-build-deb.sh"

    - name: Create and Push Tag
      env:
        VERSION: ${{ env.VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if the tag exists remotely
        if git ls-remote --tags origin | grep -q "refs/tags/deb/$VERSION$"; then
          echo "Tag deb/$VERSION already exists. Skipping tag creation."
        else
          # Create and push the debian tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag deb/$VERSION
          git push origin deb/$VERSION
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: deb/${{ env.VERSION }}
        files: |
          aiv*.deb
